package com.cleanmanager.widget;
import android.content.*;import org.json.*;import java.io.*;import java.net.*;import java.time.*;import java.util.*;
final class ScheduleRepository {
 static class Ev {String id,title,date,time,calId,color; Ev(String i,String t,String d,String tm,String c,String col){id=i;title=t;date=d;time=tm;calId=c;color=col;}}
 static List<Ev> load(Context c,LocalDate from,LocalDate to){String cid=c.getSharedPreferences("cm",Context.MODE_PRIVATE).getString("companyId","");ArrayList<Ev> out=new ArrayList<>();if(cid.isEmpty())return out;try{Map<String,String> colors=loadCalColors(cid);String u="https://firestore.googleapis.com/v1/projects/clean-manager-60bc9/databases/(default)/documents/companies/"+URLEncoder.encode(cid,"UTF-8")+"/events?pageSize=1000";HttpURLConnection x=(HttpURLConnection)new URL(u).openConnection();x.setConnectTimeout(7000);x.setReadTimeout(7000);BufferedReader br=new BufferedReader(new InputStreamReader(x.getInputStream()));StringBuilder sb=new StringBuilder();for(String s;(s=br.readLine())!=null;)sb.append(s);JSONObject root=new JSONObject(sb.toString());JSONArray docs=root.optJSONArray("documents");if(docs==null)return out;for(int i=0;i<docs.length();i++){JSONObject d=docs.getJSONObject(i),f=d.optJSONObject("fields");if(f==null)continue;String id=d.optString("name");id=id.substring(id.lastIndexOf('/')+1);String title=str(f,"title","일정"),start=str(f,"start",""),time=str(f,"startTime",str(f,"time","")),calId=str(f,"calId","unassigned");String color=colors.getOrDefault(calId,"#9ca3af");if(start.isEmpty())continue;LocalDate base;try{base=LocalDate.parse(start);}catch(Exception e){continue;}String repeat=str(f,"repeat","none");int interval=(int)num(f,"repeatInterval",1);String until=str(f,"repeatUntil","");LocalDate end=until.isEmpty()?to:LocalDate.parse(until);if(end.isAfter(to))end=to;if(repeat.equals("none")||repeat.isEmpty()){if(!base.isBefore(from)&&!base.isAfter(to))out.add(new Ev(id,title,start,time,calId,color));continue;}for(LocalDate cur=base;!cur.isAfter(end);cur=next(cur,repeat,interval)){if(!cur.isBefore(from)&&!cur.isAfter(to))out.add(new Ev(id,title,cur.toString(),time,calId,color));if(cur.isAfter(to))break;}}
 }catch(Exception ignored){}out.sort((a,b)->(a.date+a.time).compareTo(b.date+b.time));return out;}
 static Map<String,String> loadCalColors(String cid){HashMap<String,String> out=new HashMap<>();out.put("clean0","#1a56db");out.put("clean1","#16a34a");out.put("clean2","#ea580c");out.put("unassigned","#9ca3af");try{String u="https://firestore.googleapis.com/v1/projects/clean-manager-60bc9/databases/(default)/documents/companies/"+URLEncoder.encode(cid,"UTF-8")+"/cals?pageSize=200";HttpURLConnection x=(HttpURLConnection)new URL(u).openConnection();x.setConnectTimeout(5000);x.setReadTimeout(5000);BufferedReader br=new BufferedReader(new InputStreamReader(x.getInputStream()));StringBuilder sb=new StringBuilder();for(String s;(s=br.readLine())!=null;)sb.append(s);JSONArray docs=new JSONObject(sb.toString()).optJSONArray("documents");if(docs==null)return out;for(int i=0;i<docs.length();i++){JSONObject d=docs.getJSONObject(i),f=d.optJSONObject("fields");if(f==null)continue;String name=d.optString("name"),id=name.substring(name.lastIndexOf('/')+1),color=str(f,"color","");if(!color.isEmpty())out.put(id,color);}}catch(Exception ignored){}return out;}
 static LocalDate next(LocalDate d,String r,int n){n=Math.max(1,n);if(r.contains("week"))return d.plusWeeks(n);if(r.contains("month"))return d.plusMonths(n);if(r.contains("year"))return d.plusYears(n);return d.plusDays(n);}
 static String str(JSONObject f,String k,String def){JSONObject v=f.optJSONObject(k);if(v==null)return def;if(v.has("stringValue"))return v.optString("stringValue",def);return def;}
 static long num(JSONObject f,String k,long def){JSONObject v=f.optJSONObject(k);if(v==null)return def;try{return Long.parseLong(v.optString("integerValue",String.valueOf(def)));}catch(Exception e){return def;}}
}
