package com.cleanmanager.widget;
import android.content.*;import android.graphics.Color;import android.net.Uri;import android.widget.*;import java.time.*;import java.time.format.*;import java.time.temporal.*;import java.util.*;
public class WidgetPageService extends RemoteViewsService{
 public RemoteViewsFactory onGetViewFactory(Intent i){return new F(this,i.getStringExtra("mode"));}
 static class F implements RemoteViewsFactory{
  Context c;String mode;List<ScheduleRepository.Ev> evs=new ArrayList<>();LocalDate today=LocalDate.now();
  int[] colors={Color.rgb(231,245,238),Color.rgb(232,240,254),Color.rgb(255,244,229),Color.rgb(243,234,252),Color.rgb(255,235,238)};
  F(Context c,String m){this.c=c;mode=m==null?"daily":m;} public void onCreate(){load();}public void onDataSetChanged(){load();}void load(){evs=ScheduleRepository.load(c,today.minusMonths(2),today.plusMonths(4));}public void onDestroy(){}public int getCount(){return mode.equals("daily")?15:mode.equals("weekly")?9:7;}public long getItemId(int p){return p;}public boolean hasStableIds(){return true;}public int getViewTypeCount(){return 1;}public RemoteViews getLoadingView(){return null;}
  public RemoteViews getViewAt(int p){return mode.equals("daily")?daily(p):mode.equals("weekly")?weekly(p):monthly(p);}
  RemoteViews daily(int p){LocalDate d=today.plusDays(p-3);RemoteViews r=new RemoteViews(c.getPackageName(),R.layout.page_daily);r.setTextViewText(R.id.title,labelDay(d));StringBuilder b=new StringBuilder();int n=0;for(ScheduleRepository.Ev e:evs)if(e.date.equals(d.toString())){b.append(e.time.isEmpty()?"":e.time+"  ").append(e.title).append("\n");n++;}if(n==0)b.append("일정 없음");r.setTextViewText(R.id.body,b.toString().trim());Intent f=dateIntent(d);r.setOnClickFillInIntent(R.id.body,f);return r;}
  RemoteViews weekly(int p){LocalDate base=today.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)).plusWeeks(p-2);RemoteViews r=new RemoteViews(c.getPackageName(),R.layout.page_weekly);r.setTextViewText(R.id.title,base.format(DateTimeFormatter.ofPattern("M월 d일"))+" ~ "+base.plusDays(6).format(DateTimeFormatter.ofPattern("M월 d일")));for(int k=0;k<8;k++){RemoteViews cell=new RemoteViews(c.getPackageName(),R.layout.week_cell);if(k<7){LocalDate d=base.plusDays(k);String[] ko={"월","화","수","목","금","토","일"};cell.setTextViewText(R.id.cell_date,ko[k]+"  "+d.format(DateTimeFormatter.ofPattern("M/d")));List<ScheduleRepository.Ev> ds=day(d);for(int q=0;q<Math.min(6,ds.size());q++){RemoteViews chip=chip(ds.get(q),q,true);cell.addView(R.id.cell_events,chip);}if(ds.size()>6){RemoteViews more=new RemoteViews(c.getPackageName(),R.layout.event_chip);more.setTextViewText(R.id.chip,"+"+(ds.size()-6)+"개 더");more.setInt(R.id.chip,"setBackgroundColor",Color.TRANSPARENT);cell.addView(R.id.cell_events,more);}cell.setOnClickFillInIntent(R.id.cell,dateIntent(d));}else{cell.setTextViewText(R.id.cell_date,"");}r.addView(k<4?R.id.week_row1:R.id.week_row2,cell);}return r;}
  RemoteViews monthly(int p){YearMonth ym=YearMonth.from(today).plusMonths(p-2);RemoteViews r=new RemoteViews(c.getPackageName(),R.layout.page_monthly);r.setTextViewText(R.id.title,ym.format(DateTimeFormatter.ofPattern("yyyy년 M월")));LocalDate first=ym.atDay(1);int offset=first.getDayOfWeek().getValue()%7;LocalDate gridStart=first.minusDays(offset);int[] rows={R.id.month_row1,R.id.month_row2,R.id.month_row3,R.id.month_row4,R.id.month_row5,R.id.month_row6};for(int cellNo=0;cellNo<42;cellNo++){LocalDate d=gridStart.plusDays(cellNo);RemoteViews cell=new RemoteViews(c.getPackageName(),R.layout.month_cell);boolean in=d.getMonthValue()==ym.getMonthValue();cell.setTextViewText(R.id.cell_date,String.valueOf(d.getDayOfMonth()));int col=cellNo%7;int tc=!in?Color.rgb(190,194,201):col==0?Color.rgb(232,76,99):col==6?Color.rgb(79,114,232):Color.rgb(48,49,52);cell.setTextColor(R.id.cell_date,tc);List<ScheduleRepository.Ev> ds=day(d);for(int q=0;q<Math.min(3,ds.size());q++){RemoteViews chip=chip(ds.get(q),q,false);if(!in)chip.setTextColor(R.id.chip,Color.rgb(175,180,188));cell.addView(R.id.cell_events,chip);}if(ds.size()>3){RemoteViews more=new RemoteViews(c.getPackageName(),R.layout.event_chip);more.setTextViewText(R.id.chip,"+"+(ds.size()-3));more.setInt(R.id.chip,"setBackgroundColor",Color.TRANSPARENT);cell.addView(R.id.cell_events,more);}cell.setOnClickFillInIntent(R.id.cell,dateIntent(d));r.addView(rows[cellNo/7],cell);}return r;}
  RemoteViews chip(ScheduleRepository.Ev e,int i,boolean withTime){RemoteViews x=new RemoteViews(c.getPackageName(),R.layout.event_chip);String t=(withTime&&!e.time.isEmpty()?e.time+" ":"")+e.title;x.setTextViewText(R.id.chip,t);x.setInt(R.id.chip,"setBackgroundColor",colors[i%colors.length]);try{x.setOnClickFillInIntent(R.id.chip,dateIntent(LocalDate.parse(e.date)));}catch(Exception ignored){}return x;}
  Intent dateIntent(LocalDate d){Intent f=new Intent();f.setData(Uri.parse(WidgetUtil.WEB+"?widgetDate="+d));return f;}
  List<ScheduleRepository.Ev> day(LocalDate d){ArrayList<ScheduleRepository.Ev>a=new ArrayList<>();for(ScheduleRepository.Ev e:evs)if(e.date.equals(d.toString()))a.add(e);a.sort(Comparator.comparing(x->x.time==null?"":x.time));return a;}
  String labelDay(LocalDate d){String[]w={"월","화","수","목","금","토","일"};String rel=d.equals(today)?"오늘 · ":d.equals(today.plusDays(1))?"내일 · ":d.equals(today.minusDays(1))?"어제 · ":"";return rel+d.format(DateTimeFormatter.ofPattern("M월 d일"))+" ("+w[d.getDayOfWeek().getValue()-1]+")";}
 }
}
