package com.cleanmanager.widget;
import android.content.*;import android.widget.*;import java.time.*;import java.time.format.*;import java.time.temporal.*;import java.util.*;
public class WidgetPageService extends RemoteViewsService {public RemoteViewsFactory onGetViewFactory(Intent i){return new F(this,i.getStringExtra("mode"));}
 static class F implements RemoteViewsFactory {Context c;String mode;List<ScheduleRepository.Ev> evs=new ArrayList<>();LocalDate today=LocalDate.now();F(Context c,String m){this.c=c;mode=m==null?"daily":m;}public void onCreate(){load();}public void onDataSetChanged(){load();}void load(){evs=ScheduleRepository.load(c,today.minusMonths(2),today.plusMonths(4));}public void onDestroy(){}public int getCount(){return mode.equals("daily")?15:mode.equals("weekly")?9:7;}public long getItemId(int p){return p;}public boolean hasStableIds(){return true;}public int getViewTypeCount(){return 1;}public RemoteViews getLoadingView(){return null;}
 public RemoteViews getViewAt(int p){return mode.equals("daily")?daily(p):mode.equals("weekly")?weekly(p):monthly(p);} 
 RemoteViews daily(int p){LocalDate d=today.plusDays(p-3);RemoteViews r=new RemoteViews(c.getPackageName(),R.layout.page_daily);r.setTextViewText(R.id.title,labelDay(d));StringBuilder b=new StringBuilder();int n=0;for(ScheduleRepository.Ev e:evs)if(e.date.equals(d.toString())){b.append(e.time.isEmpty()?"":e.time+"  ").append(e.title).append("\n");n++;}if(n==0)b.append("일정 없음");r.setTextViewText(R.id.body,b.toString().trim());return r;}
 RemoteViews weekly(int p){LocalDate base=today.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)).plusWeeks(p-2);RemoteViews r=new RemoteViews(c.getPackageName(),R.layout.page_weekly);r.setTextViewText(R.id.title,base.format(DateTimeFormatter.ofPattern("M월 d일"))+" ~ "+base.plusDays(6).format(DateTimeFormatter.ofPattern("M월 d일")));StringBuilder b=new StringBuilder();String[] ko={"월","화","수","목","금","토","일"};for(int k=0;k<7;k++){LocalDate d=base.plusDays(k);List<ScheduleRepository.Ev> day=day(d);b.append(ko[k]).append(" ").append(d.getDayOfMonth()).append("  ");if(day.isEmpty())b.append("—");else{for(int q=0;q<Math.min(2,day.size());q++){if(q>0)b.append(" / ");b.append(day.get(q).title);}if(day.size()>2)b.append(" +").append(day.size()-2);}b.append("\n");}r.setTextViewText(R.id.body,b.toString().trim());return r;}
 RemoteViews monthly(int p){YearMonth ym=YearMonth.from(today).plusMonths(p-2);RemoteViews r=new RemoteViews(c.getPackageName(),R.layout.page_monthly);r.setTextViewText(R.id.title,ym.format(DateTimeFormatter.ofPattern("yyyy년 M월")));LocalDate first=ym.atDay(1);int offset=first.getDayOfWeek().getValue()%7,days=ym.lengthOfMonth();StringBuilder b=new StringBuilder();for(int cell=0;cell<42;cell++){int day=cell-offset+1;String s="    ";if(day>=1&&day<=days){LocalDate d=ym.atDay(day);boolean has=!day(d).isEmpty();s=String.format(Locale.KOREA,"%2d%s",day,has?"•":" ");}b.append(s);if(cell%7==6)b.append("\n");else b.append(" ");}r.setTextViewText(R.id.body,b.toString().trim());return r;}
 List<ScheduleRepository.Ev> day(LocalDate d){ArrayList<ScheduleRepository.Ev> a=new ArrayList<>();for(ScheduleRepository.Ev e:evs)if(e.date.equals(d.toString()))a.add(e);return a;}
 String labelDay(LocalDate d){String[] w={"월","화","수","목","금","토","일"};String rel=d.equals(today)?"오늘 · ":d.equals(today.plusDays(1))?"내일 · ":d.equals(today.minusDays(1))?"어제 · ":"";return rel+d.format(DateTimeFormatter.ofPattern("M월 d일"))+" ("+w[d.getDayOfWeek().getValue()-1]+")";}
 }}
